<h2>Sign up using this form</h2>

<?php echo $this->tag->form("signup/register"); ?>

    <div class="form-group">
        <label for="name">Name</label>
      
        <?php echo $this->tag->textField([
        
            "name",
            "class"=>"form-control",
            "placeholder"=>"Enter your name"
        ]); ?>
    </div>


    <div class="form-group">
        <label for="email">E-Mail</label>
        <?php echo $this->tag->textField([
        
            "email",
            "class"=>"form-control",
            "placeholder"=>"Enter your email"
        
        ]); ?>
    </div>

    <div class="form-group">
        <label for="password">Password</label>
        <?php echo $this->tag->textField([
        
            "password",
            "class"=>"form-control",
            "placeholder"=>"Enter your password"
        
        ]); ?>
    </div>

   
    

    <div class="form-group">
        <?php echo $this->tag->submitButton(
        [
        "value" => "Register",
        "class"=>"btn btn-primary"
        ]); ?>
    </div>

</form>